services:
  - type: web
    name: sistema-pacientes
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: "18.20.4"
    envVars:
      - key: NODE_ENV
        value: production